### PR TITLE
C-statistic using weights

### PR DESCRIPTION
**Pull request by StatsFizz**
This contains a correction to the C-statistic calculation using weights to account for the sampling used.

This also required a few ado files to be added.

Note: I haven't run this to check it works - I don't have input.csv any more etc. But it should work. It's enough that we could retrieve what we did if we need to!

### CODE REVIEW

**Comment by krishnanbhaskaran** [comment]
hi - is this what you ran on the server to get the final corrected C?

I can't see any ado files in this PR - should there be some in there, e.g. somersd?

**Comment by StatsFizz** [comment]
Yes. And there should be a folder called “ado” with the somersd files…?

**Comment by krishnanbhaskaran** [comment]
is your github picking up the subfolder? There is only the do-file under "files changed" here. Maybe just put the ado files into the main analysis folder? I have had trouble with getting github to recognise subfolders before.

**Comment by StatsFizz** [comment]
Hmm… yes, I can see them. Maybe they were blocked by the gitignore. I’ve now added to the main analysis folder instead…

**Review by krishnanbhaskaran — APPROVED** [review]

**Pull request merged**
